// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Garage_Management.Models;

public partial class GarageVisit
{
    [Key]
    [Column("VisitID")]
    public int VisitId { get; set; }

    [Column("CustomerID")]
    public int? CustomerId { get; set; }

    [Column("GarageID")]
    public int? GarageId { get; set; }

    public DateOnly? VisitDate { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string ServiceDescription { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? TotalCost { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("GarageVisits")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("GarageId")]
    [InverseProperty("GarageVisits")]
    public virtual Garage Garage { get; set; }
}