// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Garage_Management.Models;

public partial class GaragePermission
{
    [Key]
    [Column("PermissionID")]
    public int PermissionId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column("GarageID")]
    public int? GarageId { get; set; }

    public bool? CanView { get; set; }

    public bool? CanEdit { get; set; }

    [ForeignKey("GarageId")]
    [InverseProperty("GaragePermissions")]
    public virtual Garage Garage { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("GaragePermissions")]
    public virtual User User { get; set; }
}