// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Garage_Management.Models;

[Table("Garage")]
public partial class Garage
{
    [Key]
    [Column("GarageID")]
    public int GarageId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string GarageName { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [InverseProperty("Garage")]
    public virtual ICollection<GaragePermission> GaragePermissions { get; set; } = new List<GaragePermission>();

    [InverseProperty("Garage")]
    public virtual ICollection<GarageVisit> GarageVisits { get; set; } = new List<GarageVisit>();
}