// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Garage_Management.Models;

public partial class Garage_ManagementContext : DbContext
{
    public Garage_ManagementContext()
    {
    }

    public Garage_ManagementContext(DbContextOptions<Garage_ManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Garage> Garages { get; set; }

    public virtual DbSet<GaragePermission> GaragePermissions { get; set; }

    public virtual DbSet<GarageVisit> GarageVisits { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-1TO5NHM\\SQLEXPRESS;Initial Catalog=Garage_Management;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64B8E163A53C");

            entity.Property(e => e.CustomerId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Garage>(entity =>
        {
            entity.HasKey(e => e.GarageId).HasName("PK__Garage__5D8BEEB19BD52655");

            entity.Property(e => e.GarageId).ValueGeneratedNever();
        });

        modelBuilder.Entity<GaragePermission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK__GaragePe__EFA6FB0F94D1FA78");

            entity.Property(e => e.PermissionId).ValueGeneratedNever();

            entity.HasOne(d => d.Garage).WithMany(p => p.GaragePermissions).HasConstraintName("FK__GaragePer__Garag__4AB81AF0");

            entity.HasOne(d => d.User).WithMany(p => p.GaragePermissions).HasConstraintName("FK__GaragePer__UserI__49C3F6B7");
        });

        modelBuilder.Entity<GarageVisit>(entity =>
        {
            entity.HasKey(e => e.VisitId).HasName("PK__GarageVi__4D3AA1BE26437AE1");

            entity.Property(e => e.VisitId).ValueGeneratedNever();

            entity.HasOne(d => d.Customer).WithMany(p => p.GarageVisits).HasConstraintName("FK__GarageVis__Custo__45F365D3");

            entity.HasOne(d => d.Garage).WithMany(p => p.GarageVisits).HasConstraintName("FK__GarageVis__Garag__46E78A0C");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK__Permissi__EFA6FB0F8CADF1C7");

            entity.Property(e => e.PermissionId).ValueGeneratedNever();

            entity.HasOne(d => d.Customer).WithMany(p => p.Permissions).HasConstraintName("FK__Permissio__Custo__3D5E1FD2");

            entity.HasOne(d => d.User).WithMany(p => p.Permissions).HasConstraintName("FK__Permissio__UserI__3C69FB99");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACB7A4CD02");

            entity.Property(e => e.UserId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__Vehicles__476B54B2190F3DDC");

            entity.Property(e => e.VehicleId).ValueGeneratedNever();

            entity.HasOne(d => d.Owner).WithMany(p => p.Vehicles).HasConstraintName("FK__Vehicles__OwnerI__412EB0B6");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}