// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Garage_Management.Models;

public partial class Permission
{
    [Key]
    [Column("PermissionID")]
    public int PermissionId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column("CustomerID")]
    public int? CustomerId { get; set; }

    public bool? CanView { get; set; }

    public bool? CanEdit { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Permissions")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Permissions")]
    public virtual User User { get; set; }
}