// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Garage_Management.Models;

public partial class User
{
    [Key]
    [Column("UserID")]
    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<GaragePermission> GaragePermissions { get; set; } = new List<GaragePermission>();

    [InverseProperty("User")]
    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}