// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Garage_Management.Models;

[Index("Vin", Name = "UQ__Vehicles__C5DF234C10FF01C7", IsUnique = true)]
public partial class Vehicle
{
    [Key]
    [Column("VehicleID")]
    public int VehicleId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Make { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Model { get; set; }

    public int? Year { get; set; }

    [Column("VIN")]
    [StringLength(17)]
    [Unicode(false)]
    public string Vin { get; set; }

    public int? Mileage { get; set; }

    public DateOnly? LastServiceDate { get; set; }

    [Column("OwnerID")]
    public int? OwnerId { get; set; }

    [ForeignKey("OwnerId")]
    [InverseProperty("Vehicles")]
    public virtual Customer Owner { get; set; }
}